// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeyt839rDGcoH3LwRWuc65_CUg6D6S5XE',
    appId: '1:745412020745:web:8f3fdda7dc122c752c86d8',
    messagingSenderId: '745412020745',
    projectId: 'test-8cd9e',
    authDomain: 'test-8cd9e.firebaseapp.com',
    storageBucket: 'test-8cd9e.firebasestorage.app',
    measurementId: 'G-EJW6EMNGQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCF8ca5L5WEXYW9XdNRYmwp0j8vpUTh0',
    appId: '1:745412020745:android:27fd06484220adb62c86d8',
    messagingSenderId: '745412020745',
    projectId: 'test-8cd9e',
    storageBucket: 'test-8cd9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_t2-wFOXuaMTgcKP9ltVsFuyOhU8CqvU',
    appId: '1:745412020745:ios:a1375b2e55147dc32c86d8',
    messagingSenderId: '745412020745',
    projectId: 'test-8cd9e',
    storageBucket: 'test-8cd9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_t2-wFOXuaMTgcKP9ltVsFuyOhU8CqvU',
    appId: '1:745412020745:ios:a1375b2e55147dc32c86d8',
    messagingSenderId: '745412020745',
    projectId: 'test-8cd9e',
    storageBucket: 'test-8cd9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeyt839rDGcoH3LwRWuc65_CUg6D6S5XE',
    appId: '1:745412020745:web:621677e81dc3ab082c86d8',
    messagingSenderId: '745412020745',
    projectId: 'test-8cd9e',
    authDomain: 'test-8cd9e.firebaseapp.com',
    storageBucket: 'test-8cd9e.firebasestorage.app',
    measurementId: 'G-F14DEYNMM9',
  );
}
